### ISSUE TITLE
java.lang.IllegalStateException: getWriter() has already been called for this response

### ISSUE THREAD

**Issue by kondamudi** [onelogin/java-saml#173]
auth.login(); method is giving following error. This is occurring only on server(glassfish) but not in local machine.
 
java.lang.IllegalStateException: getWriter() has already been called for this response
	at org.apache.catalina.connector.Response.getOutputStream(Response.java:746)
	at org.apache.catalina.connector.ResponseFacade.getOutputStream(ResponseFacade.java:206)
	at org.springframework.http.server.ServletServerHttpResponse.getBody(ServletServerHttpResponse.java:88)
	at org.springframework.http.converter.json.AbstractJackson2HttpMessageConverter.writeInternal(AbstractJackson2HttpMessageConverter.java:234)
	at org.springframework.http.converter.AbstractGenericHttpMessageConverter.write(AbstractGenericHttpMessageConverter.java:100)
	at org.springframework.web.servlet.mvc.method.annotation.AbstractMessageConverterMethodProcessor.writeWithMessageConverters(AbstractMessageConverterMethodProcessor.java:222)
	at org.springframework.web.servlet.mvc.method.annotation.HttpEntityMethodProcessor.handleReturnValue(HttpEntityMethodProcessor.java:183)
	at org.springframework.web.method.support.HandlerMethodReturnValueHandlerComposite.handleReturnValue(HandlerMethodReturnValueHandlerComposite.java:80)
	at org.springframework.web.servlet.mvc.method.annotation.ServletInvocableHandlerMethod.invokeAndHandle(ServletInvocableHandlerMethod.java:126)
	at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.invokeHandlerMethod(RequestMappingHandlerAdapter.java:814)
	at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.handleInternal(RequestMappingHandlerAdapter.java:737)
	at org.springframework.web.servlet.mvc.method.AbstractHandlerMethodAdapter.handle(AbstractHandlerMethodAdapter.java:85)
	at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:959)
	at org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:893)
	at org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:969)
	at org.springframework.web.servlet.FrameworkServlet.doGet(FrameworkServlet.java:860)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:687)
	at org.springframework.web.servlet.FrameworkServlet.service(FrameworkServlet.java:845)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:790)
	at org.apache.catalina.core.StandardWrapper.service(StandardWrapper.java:1682)
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:318)
	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:160)
	at org.apache.catalina.core.StandardPipeline.doInvoke(StandardPipeline.java:734)
	at org.apache.catalina.core.StandardPipeline.invoke(StandardPipeline.java:673)
	at com.sun.enterprise.web.WebPipeline.invoke(WebPipeline.java:99)
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:174)
	at org.apache.catalina.core.StandardPipeline.doInvoke(StandardPipeline.java:734)
	at org.apache.catalina.core.StandardPipeline.invoke(StandardPipeline.java:673)
	at org.apache.catalina.connector.CoyoteAdapter.doService(CoyoteAdapter.java:412)
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:282)
	at com.sun.enterprise.v3.services.impl.ContainerMapper$HttpHandlerCallable.call(ContainerMapper.java:459)
	at com.sun.enterprise.v3.services.impl.ContainerMapper.service(ContainerMapper.java:167)
	at org.glassfish.grizzly.http.server.HttpHandler.runService(HttpHandler.java:201)
	at org.glassfish.grizzly.http.server.HttpHandler.doHandle(HttpHandler.java:175)
	at org.glassfish.grizzly.http.server.HttpServerFilter.handleRead(HttpServerFilter.java:235)
	at org.glassfish.grizzly.filterchain.ExecutorResolver$9.execute(ExecutorResolver.java:119)
	at org.glassfish.grizzly.filterchain.DefaultFilterChain.executeFilter(DefaultFilterChain.java:284)
	at org.glassfish.grizzly.filterchain.DefaultFilterChain.executeChainPart(DefaultFilterChain.java:201)
	at org.glassfish.grizzly.filterchain.DefaultFilterChain.execute(DefaultFilterChain.java:133)
	at org.glassfish.grizzly.filterchain.DefaultFilterChain.process(DefaultFilterChain.java:112)
	at org.glassfish.grizzly.ProcessorExecutor.execute(ProcessorExecutor.java:77)
	at org.glassfish.grizzly.nio.transport.TCPNIOTransport.fireIOEvent(TCPNIOTransport.java:561)
	at org.glassfish.grizzly.strategies.AbstractIOStrategy.fireIOEvent(AbstractIOStrategy.java:112)
	at org.glassfish.grizzly.strategies.WorkerThreadIOStrategy.run0(WorkerThreadIOStrategy.java:117)
	at org.glassfish.grizzly.strategies.WorkerThreadIOStrategy.access$100(WorkerThreadIOStrategy.java:56)
	at org.glassfish.grizzly.strategies.WorkerThreadIOStrategy$WorkerThreadRunnable.run(WorkerThreadIOStrategy.java:137)
	at org.glassfish.grizzly.threadpool.AbstractThreadPool$Worker.doWork(AbstractThreadPool.java:565)
	at org.glassfish.grizzly.threadpool.AbstractThreadPool$Worker.run(AbstractThreadPool.java:545)
	at java.lang.Thread.run(Thread.java:745)]]

**Comment by pitbulk** [comment]
I don't see how that is related with java-saml.

**Comment by kondamudi** [comment]
auth.login();  -> This method is in Auth class of package com.onelogin.saml2

**Comment by pitbulk** [comment]
I guess in your view you are printing something, but the auth.login() method is a redirection and requires nothing to be printed previously.

Can you try to execute something similar to the [example](https://github.com/onelogin/java-saml/blob/master/samples/java-saml-tookit-jspsample/src/main/webapp/dologin.jsp)?

**Comment by kondamudi** [comment]
i am using same code but only returning response as ResponsEntity
public ResponseEntity<String> SAMLAuthenticate(HttpServletRequest request, HttpServletResponse response) throws Exception { 
		LOGGER.debug("Inside SAMLAuthenticate");
		Auth auth = new Auth(request, response);
		if (request.getParameter("attrs") == null) {
			LOGGER.info("Accessing IDP login page");
			auth.login();  **-> This is the place where error is throwing out. I commented this and i m able to see the response as Success  in browser.**
		} else {
			LOGGER.info("User already authenticated");
			String x = request.getPathInfo();
			LOGGER.info("Path: " + request.getPathInfo());
			auth.login("/");
		}
		LOGGER.info("exiting SAMLAuthenticate");
		return new ResponseEntity<String>("Success", HttpStatus.OK);
	}

**Comment by kondamudi** [comment]
@pitbulk - Is this really an issues with onelogin?

**Comment by pitbulk** [comment]
As [ServletResponse](http://tomcat.apache.org/tomcat-5.5-doc/servletapi/javax/servlet/ServletResponse.html
) the method getOutputStream definition says:
```
public ServletOutputStream getOutputStream() throws java.io.IOException

Returns a ServletOutputStream suitable for writing binary data in the response. The servlet container does not encode the binary data.

Calling flush() on the ServletOutputStream commits the response. Either this method or getWriter() may be called to write the body, not both.

Returns:   a ServletOutputStream for writing binary data

Throws:    java.lang.IllegalStateException - if the getWriter method has been called on this response
```

The [getWriter](http://tomcat.apache.org/tomcat-5.5-doc/servletapi/javax/servlet/ServletResponse.html#getWriter()) definition says:
```
Throws:  java.lang.IllegalStateException - if the getOutputStream method has already been called for this response object
```

So basically you can't call in the same thread to getWriter and getOutputStream.

If you review the method
```
auth.login()
```
It executes a redirection with
```
ServletUtils.sendRedirect(response, ssoUrl, parameters, stay);
```
if you don't set stay = True

so your code
```
return new ResponseEntity<String>("Success", HttpStatus.OK);
```
will never be executed.


javax.servlet.http.HttpServletResponse.sendRedirect uses getWriter and that why you experience the error.
