### ISSUE TITLE
java.lang.NoClassDefFoundError: Could not initialize class com.onelogin.saml2.util.Util

### ISSUE THREAD

**Issue by aii-goto-yusaku** [onelogin/java-saml#247]
Environment: GlassFish4.1.2
pom.xml
```
<dependency>
	<groupId>com.onelogin</groupId>
	<artifactId>java-saml</artifactId>
	<version>2.5.0</version>
</dependency>
```

This is my code written in Servlet Filter.
```
Properties properties = SamlEnv.getProperties();
new SettingsBuilder().fromProperties(properties).build();
```

Then the following error occurs.
```
java.lang.NoClassDefFoundError: Could not initialize class com.onelogin.saml2.util.Util
	at com.onelogin.saml2.settings.SettingsBuilder.loadCertificateFromProp(SettingsBuilder.java:534)
	at com.onelogin.saml2.settings.SettingsBuilder.loadCertificateFromProp(SettingsBuilder.java:557)
	at com.onelogin.saml2.settings.SettingsBuilder.loadSpSetting(SettingsBuilder.java:425)
	at com.onelogin.saml2.settings.SettingsBuilder.build(SettingsBuilder.java:201)
	at com.onelogin.saml2.settings.SettingsBuilder.build(SettingsBuilder.java:177)
```

It seems that an error has occurred when trying to call Util#loadCert in SettingBuilder#loadCertificateFromProp.
But I don't know any more. Help me.
```
protected X509Certificate loadCertificateFromProp(Object propValue) {
    if (this.isString(propValue)) {
        try {
            return Util.loadCert(((String)propValue).trim());   // <-- Applicable part !
        } catch (CertificateException var3) {
            LOGGER.error("Error loading certificate from properties.", var3);
            return null;
        }
    } else {
        return propValue instanceof X509Certificate ? (X509Certificate)propValue : null;
    }
}
```

**Comment by sunkaiqin** [comment]
It looks like you don't have configured the cert yet. Have you checked if you have the cert configured?

**Comment by aii-goto-yusaku** [comment]
The path for `onelogin.saml2.sp.x509cert` was incorrect.
When I fixed this, it was another warning.
Since this seems to be another problem, this issue will be closed.

I was saved. Thank you.

```
[2019-11-15T10:26:11.319+0900] [glassfish 4.1] [WARNING] [] [javax.enterprise.web] [tid: _ThreadID=35 _ThreadName=http-listener-1(5)] [timeMillis: 1573781171319] [levelValue: 900] [[
  StandardWrapperValve[login]: Servlet.service() for servlet login threw exception
java.lang.ClassNotFoundException: org.apache.commons.logging.LogFactory not found by org.glassfish.metro.webservices-osgi [34]
	at org.apache.felix.framework.BundleWiringImpl.findClassOrResourceByDelegation(BundleWiringImpl.java:1532)
	at org.apache.felix.framework.BundleWiringImpl.access$400(BundleWiringImpl.java:75)
	at org.apache.felix.framework.BundleWiringImpl$BundleClassLoader.loadClass(BundleWiringImpl.java:1955)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	at org.apache.xml.security.Init.<clinit>(Init.java:59)
	at com.onelogin.saml2.util.Util.<clinit>(Util.java:117)
	at com.onelogin.saml2.settings.SettingsBuilder.loadCertificateFromProp(SettingsBuilder.java:534)
	at com.onelogin.saml2.settings.SettingsBuilder.loadCertificateFromProp(SettingsBuilder.java:557)
	at com.onelogin.saml2.settings.SettingsBuilder.loadSpSetting(SettingsBuilder.java:425)
	at com.onelogin.saml2.settings.SettingsBuilder.build(SettingsBuilder.java:201)
	at com.onelogin.saml2.settings.SettingsBuilder.build(SettingsBuilder.java:177)
```
