### ISSUE TITLE
Integrate Java App with ADFS

### ISSUE THREAD

**Issue by enricovena** [onelogin/java-saml#249]
I have this Windows 2019 environment: 1 DC, 1 Root CA abd 1 ADFS node (all endpoints are https with certificate released from root ca). I have another windows 10 test environment with Eclipse and Tomcat (in SSL with a certificate released from root ca). I have deployed  java-saml-tookit-jspsample on Tomcat in ssl and registered the relying party trust in ADFS. When I run login in jspsample I am correctly redirected to adfs sso page and then I make login in adfs. Afeter login, when the response come back to /java-saml-tookit-jspsample/acs.jsp I have this error:
```
[https-openssl-nio-443-exec-7] WARN com.onelogin.saml2.util.Util - Error executing validateSignNode: Signature length not correct: got 256 but was expecting 512
org.apache.xml.security.signature.XMLSignatureException: Signature length not correct: got 256 but was expecting 512
Original Exception was java.security.SignatureException: Signature length not correct: got 256 but was expecting 512
	at org.apache.xml.security.algorithms.implementations.SignatureBaseRSA.engineVerify(SignatureBaseRSA.java:92)
	at org.apache.xml.security.algorithms.SignatureAlgorithm.verify(SignatureAlgorithm.java:301)
	at org.apache.xml.security.signature.XMLSignature.checkSignatureValue(XMLSignature.java:760)
	at org.apache.xml.security.signature.XMLSignature.checkSignatureValue(XMLSignature.java:697)
	at com.onelogin.saml2.util.Util.validateSignNode(Util.java:1010)
	at com.onelogin.saml2.util.Util.validateSign(Util.java:931)
	at com.onelogin.saml2.authn.SamlResponse.isValid(SamlResponse.java:306)
	at com.onelogin.saml2.Auth.processResponse(Auth.java:666)
	at com.onelogin.saml2.Auth.processResponse(Auth.java:699)
	at org.apache.jsp.acs_jsp._jspService(acs_jsp.java:160)
	at org.apache.jasper.runtime.HttpJspBase.service(HttpJspBase.java:70)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:741)
	at org.apache.jasper.servlet.JspServletWrapper.service(JspServletWrapper.java:476)
	at org.apache.jasper.servlet.JspServlet.serviceJspFile(JspServlet.java:385)
	at org.apache.jasper.servlet.JspServlet.service(JspServlet.java:329)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:741)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:231)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:53)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:202)
	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:96)
	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:526)
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:139)
	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:92)
	at org.apache.catalina.valves.AbstractAccessLogValve.invoke(AbstractAccessLogValve.java:678)
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:74)
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:343)
	at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:408)
	at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:66)
	at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:860)
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1589)
	at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
	at java.lang.Thread.run(Unknown Source)
Caused by: java.security.SignatureException: Signature length not correct: got 256 but was expecting 512
	at sun.security.rsa.RSASignature.engineVerify(Unknown Source)
	at java.security.Signature$Delegate.engineVerify(Unknown Source)
	at java.security.Signature.verify(Unknown Source)
	at org.apache.xml.security.algorithms.implementations.SignatureBaseRSA.engineVerify(SignatureBaseRSA.java:90)
	... 37 more
[https-openssl-nio-443-exec-7] ERROR com.onelogin.saml2.authn.SamlResponse - Signature validation failed. SAML Response rejected
[https-openssl-nio-443-exec-7] ERROR com.onelogin.saml2.Auth - processResponse error. invalid_response
```
This is the onelogin.saml.properties:
```
#  If 'strict' is True, then the Java Toolkit will reject unsigned
#  or unencrypted messages if it expects them signed or encrypted
#  Also will reject the messages if not strictly follow the SAML
onelogin.saml2.strict =  false

# Enable debug mode (to print errors)
onelogin.saml2.debug =  true


#  Service Provider Data that we are deploying
#

#  Identifier of the SP entity  (must be a URI)
onelogin.saml2.sp.entityid = https://w10develop.sirfinfarm.it/java-saml-tookit-jspsample/metadata.jsp

# Specifies info about where and how the <AuthnResponse> message MUST be
#  returned to the requester, in this case our SP.
# URL Location where the <Response> from the IdP will be returned
onelogin.saml2.sp.assertion_consumer_service.url = https://w10develop.sirfinfarm.it/java-saml-tookit-jspsample/acs.jsp

# SAML protocol binding to be used when returning the <Response>
# message.  Onelogin Toolkit supports for this endpoint the
# HTTP-POST binding only
onelogin.saml2.sp.assertion_consumer_service.binding = urn:oasis:names:tc:SAML:2.0:bindings:HTTP-POST

# Specifies info about where and how the <Logout Response> message MUST be
# returned to the requester, in this case our SP.
onelogin.saml2.sp.single_logout_service.url = https://w10develop.sirfinfarm.it/java-saml-tookit-jspsample/sls.jsp

# SAML protocol binding to be used when returning the <LogoutResponse> or sending the <LogoutRequest>
# message.  Onelogin Toolkit supports for this endpoint the
# HTTP-Redirect binding only
onelogin.saml2.sp.single_logout_service.binding = urn:oasis:names:tc:SAML:2.0:bindings:HTTP-Redirect

# Specifies constraints on the name identifier to be used to
# represent the requested subject.
# Take a look on lib/Saml2/Constants.php to see the NameIdFormat supported
onelogin.saml2.sp.nameidformat = urn:oasis:names:tc:SAML:1.1:nameid-format:unspecified

# Usually x509cert and privateKey of the SP are provided by files placed at
# the certs folder. But we can also provide them with the following parameters

onelogin.saml2.sp.x509cert = 

# Requires Format PKCS#8   BEGIN PRIVATE KEY         
# If you have     PKCS#1   BEGIN RSA PRIVATE KEY  convert it by   openssl pkcs8 -topk8 -inform pem -nocrypt -in sp.rsa_key -outform pem -out sp.pem
onelogin.saml2.sp.privatekey = 

# Identity Provider Data that we want connect with our SP
#

# Identifier of the IdP entity  (must be a URI)
onelogin.saml2.idp.entityid = https://fs.sirfinfarm.it/adfs/services/trust/mex

# SSO endpoint info of the IdP. (Authentication Request protocol)
# URL Target of the IdP where the SP will send the Authentication Request Message
onelogin.saml2.idp.single_sign_on_service.url = https://fs.sirfinfarm.it/adfs/ls

# SAML protocol binding to be used when returning the <Response>
# message.  Onelogin Toolkit supports for this endpoint the
# HTTP-Redirect binding only
onelogin.saml2.idp.single_sign_on_service.binding = urn:oasis:names:tc:SAML:2.0:bindings:HTTP-Redirect

# SLO endpoint info of the IdP.
# URL Location of the IdP where the SP will send the SLO Request
onelogin.saml2.idp.single_logout_service.url = https://fs.sirfinfarm.it/adfs/ls

# Optional SLO Response endpoint info of the IdP.
# URL Location of the IdP where the SP will send the SLO Response. If left blank, same URL as onelogin.saml2.idp.single_logout_service.url will be used.
# Some IdPs use a separate URL for sending a logout request and response, use this property to set the separate response url
onelogin.saml2.idp.single_logout_service.response.url =

# SAML protocol binding to be used when returning the <Response>
# message.  Onelogin Toolkit supports for this endpoint the
# HTTP-Redirect binding only
onelogin.saml2.idp.single_logout_service.binding = urn:oasis:names:tc:SAML:2.0:bindings:HTTP-Redirect

# Public x509 certificate of the IdP
onelogin.saml2.idp.x509cert = MIIGkTCCBXmgAwIBAgITaQAAAARuDX5XdqFD3wAAAAAABDANBgkqhkiG9w0BAQsFADBEMRIwEAYKCZImiZPyLGQBGRYCaXQxGjAYBgoJkiaJk/IsZAEZFgpzaXJmaW5mYXJtMRIwEAYDVQQDEwl3MTlyb290Y2EwHhcNMTkxMjAyMTYxMTI1WhcNMjExMjAxMTYxMTI1WjBlMQswCQYDVQQGEwJJVDELMAkGA1UECBMCSVQxEDAOBgNVBAcTB0Nvc2VuemExDzANBgNVBAoTBlNpcmZpbjEMMAoGA1UECxMDSUNUMRgwFgYDVQQDDA8qLnNpcmZpbmZhcm0uaXQwggIiMA0GCSqGSIb3DQEBAQUAA4ICDwAwggIKAoICAQDGlmh+5+zuIbI4kohv6xwLThfO6imkmLgKAML323UfGadvzjWg/sZAvZYPPKwUFvLx+h2nemRZ0zqkc/oO945hgZmd7MZrQj9WQaXoRykeVwpnART9We8bZHkWkeuV3aayEn4w5uhhKE3OGlsJ5Yy/99YQMrVSDMPzTqrnFGuytv7hMNpTXslaMSVTZcT57DgUCBoMjCEf7xyWSBwBVOvsWbQgQQ1cxB11UQYN6aJwEYysLb7ZIW1YdFtFXob8Se8+2GuYNANjrsEDpv86slbkckMX5BpYA3dwM/4ThCHOaK94B5+ZydLhNL5HghJ3CgBo2M/BavoWnhibYV8b3BBMOW10VPxQEzbu8KBpNzzYdLaGwpIh1jXvsdbcyTT0RCuSeSkBRyfqNEUe3PUwjI30fZSfipGu5GubV8L+PrtfeCaeYft8zFhNUVTV3Ozs6f7smgfhNpDFGHm2tJ/Jxa3ZajT6vrngmsvKOiVty/tGaXy/rwGX2jrxiv0MJcQth4QTiwYRbkqMffZr+wliu+JkfJrvPsohYPBmB9RHk44Go/trX+5Nx8nrSznsDlDdjtSBV2E3T6oUP9lLTPx+77sIM03/h6IlH3V2ka0SaZrf2poePBENCqdm3wmsBtVW4g+eIAADOxPPQ1TPEzquO3StBk9TPk8fCb3mTYWtawIA6QIDAQABo4ICWTCCAlUwDgYDVR0PAQH/BAQDAgWgMB0GA1UdDgQWBBS28ge6MG252YtS6B43JHJogv6UDzBBBgNVHREEOjA4ghBmcy5zaXJmaW5mYXJtLml0giRlbnRlcnByaXNlcmVnaXN0cmF0aW9uLnNpcmZpbmZhcm0uaXQwHwYDVR0jBBgwFoAUqHJyirFVmCtWfNQ31DGRWF3jLGkwgccGA1UdHwSBvzCBvDCBuaCBtqCBs4aBsGxkYXA6Ly8vQ049dzE5cm9vdGNhLENOPXcxOWNhLENOPUNEUCxDTj1QdWJsaWMlMjBLZXklMjBTZXJ2aWNlcyxDTj1TZXJ2aWNlcyxDTj1Db25maWd1cmF0aW9uLERDPXNpcmZpbmZhcm0sREM9aXQ/Y2VydGlmaWNhdGVSZXZvY2F0aW9uTGlzdD9iYXNlP29iamVjdENsYXNzPWNSTERpc3RyaWJ1dGlvblBvaW50MIG9BggrBgEFBQcBAQSBsDCBrTCBqgYIKwYBBQUHMAKGgZ1sZGFwOi8vL0NOPXcxOXJvb3RjYSxDTj1BSUEsQ049UHVibGljJTIwS2V5JTIwU2VydmljZXMsQ049U2VydmljZXMsQ049Q29uZmlndXJhdGlvbixEQz1zaXJmaW5mYXJtLERDPWl0P2NBQ2VydGlmaWNhdGU/YmFzZT9vYmplY3RDbGFzcz1jZXJ0aWZpY2F0aW9uQXV0aG9yaXR5MCEGCSsGAQQBgjcUAgQUHhIAVwBlAGIAUwBlAHIAdgBlAHIwEwYDVR0lBAwwCgYIKwYBBQUHAwEwDQYJKoZIhvcNAQELBQADggEBADdhL2UuAw0ONdTPGv/P8rTLISRvaB6tRyXTGooav+Gm0m7QuAW5Osqbh6x+Cufzr2AXf5BoPfSlQURJB4T04WUi7vtGl4ht/RxqGfEdV8NO15K2FeYXuzjzvfM+tofhowo2k+xpP8lTvEXy/R2BYqSon/d+xhXB4d+5QPmtpPQTxRHncYomLFjJxSk86MpHQLzjze2fseZ6aSwGEaMBkNzwpkAK7j0gGLpJWXWMnLLQH2QOnWWmI1e5BltPjIWTAW7DKNO6DFUj5S+ZMFdOL6TGMzxFX47GTuZRtYAFeflt74+Z7Kbn/9M3LveRkJXgm2BiIJeGkUcuPg8Pl/NEOXk=

# Instead of use the whole x509cert you can use a fingerprint
# (openssl x509 -noout -fingerprint -in "idp.crt" to generate it,
# or add for example the -sha256 , -sha384 or -sha512 parameter)
#
# If a fingerprint is provided, then the certFingerprintAlgorithm is required in order to
# let the toolkit know which Algorithm was used. Possible values: sha1, sha256, sha384 or sha512
# 'sha1' is the default value.
# onelogin.saml2.idp.certfingerprint = 
# onelogin.saml2.idp.certfingerprint_algorithm = sha1


# Security settings
#

# Indicates that the nameID of the <samlp:logoutRequest> sent by this SP
# will be encrypted.
onelogin.saml2.security.nameid_encrypted = false

# Indicates whether the <samlp:AuthnRequest> messages sent by this SP
# will be signed.              [The Metadata of the SP will offer this info]
onelogin.saml2.security.authnrequest_signed = false

# Indicates whether the <samlp:logoutRequest> messages sent by this SP
# will be signed.
onelogin.saml2.security.logoutrequest_signed = false

# Indicates whether the <samlp:logoutResponse> messages sent by this SP
# will be signed.
onelogin.saml2.security.logoutresponse_signed = false

# Indicates a requirement for the <samlp:Response>, <samlp:LogoutRequest> and
# <samlp:LogoutResponse> elements received by this SP to be signed.
onelogin.saml2.security.want_messages_signed = false

# Indicates a requirement for the <saml:Assertion> elements received by this SP to be signed.
onelogin.saml2.security.want_assertions_signed = false

# Indicates a requirement for the Metadata of this SP to be signed.
# Right now supported null (in order to not sign) or true (sign using SP private key) 
onelogin.saml2.security.sign_metadata =

# Indicates a requirement for the Assertions received by this SP to be encrypted
onelogin.saml2.security.want_assertions_encrypted = false

# Indicates a requirement for the NameID received by this SP to be encrypted
onelogin.saml2.security.want_nameid_encrypted = false

# Authentication context.
# Set Empty and no AuthContext will be sent in the AuthNRequest
# You can set multiple values (comma separated them)
onelogin.saml2.security.requested_authncontext = urn:oasis:names:tc:SAML:2.0:ac:classes:Password

# Allows the authn comparison parameter to be set, defaults to 'exact'
onelogin.saml2.security.onelogin.saml2.security.requested_authncontextcomparison = exact


# Indicates if the SP will validate all received xmls.
# (In order to validate the xml, 'strict' and 'wantXMLValidation' must be true).
onelogin.saml2.security.want_xml_validation = true

# Algorithm that the toolkit will use on signing process. Options:
#  'http://www.w3.org/2000/09/xmldsig#rsa-sha1'
#  'http://www.w3.org/2000/09/xmldsig#dsa-sha1'
#  'http://www.w3.org/2001/04/xmldsig-more#rsa-sha256'
#  'http://www.w3.org/2001/04/xmldsig-more#rsa-sha384'
#  'http://www.w3.org/2001/04/xmldsig-more#rsa-sha512'
onelogin.saml2.security.signature_algorithm = http://www.w3.org/2000/09/xmldsig#rsa-sha1

# Organization
onelogin.saml2.organization.name = SP Java 
onelogin.saml2.organization.displayname = SP Java Example
onelogin.saml2.organization.url = http://sp.sirfinfarm.it
onelogin.saml2.organization.lang = 

# Contacts
onelogin.saml2.contacts.technical.given_name = Technical Guy
onelogin.saml2.contacts.technical.email_address = technical@sirfinfarm.it
onelogin.saml2.contacts.support.given_name = Support Guy
onelogin.saml2.contacts.support.email_address = support@sirfinfarm.it
````

Can you help me?
Excuse my english. Thanks

**Comment by sunkaiqin** [comment]
I have seen this issue happening when you have mismatched certificates e.g. not the same private and public key pair. Are you sure you are using the same pair when configuring SP and IdP? 

BTW: It would be better you could format your question prettier and put less unrelated texts into the question 😄

**Comment by pitbulk** [comment]
Based on the error:
```
 Error executing validateSignNode: Signature length not correct: got 256 but was expecting 512
```

As @sunkaiqin can be related to the fact that the private key used to sign the assertion is not related to the public certificate you are using to validate it.
