### ISSUE TITLE
Trying to concurrently verify multiple responses might fail

### ISSUE THREAD

**Issue by miszobi** [onelogin/java-saml#83]
Java's SAX classes are not thread safe. Since the validation shares an instance of the `javax.xml.validation.SchemaFactory` (in `com.onelogin.saml2.util.SchemaFactory`) trying to run multiple threads validating Responses (using separate instances of `Auth` and/or `Response`) might fail with errors like:
```
org.xml.sax.SAXException: FWK005 parse may not be called while parsing.
	at com.sun.org.apache.xerces.internal.jaxp.validation.Util.toSAXException(Util.java:65) ~[na:1.7.0_71]
	at com.sun.org.apache.xerces.internal.jaxp.validation.XMLSchemaFactory.newSchema(XMLSchemaFactory.java:256) ~[na:1.7.0_71]
	at javax.xml.validation.SchemaFactory.newSchema(SchemaFactory.java:627) ~[na:1.7.0_71]
	at javax.xml.validation.SchemaFactory.newSchema(SchemaFactory.java:659) ~[na:1.7.0_71]
	at com.onelogin.saml2.util.SchemaFactory.loadFromUrl(SchemaFactory.java:25) ~[classes/:na]
	at com.onelogin.saml2.util.Util.validateXML(Util.java:215) ~[classes/:na]
```
or
```
java.lang.NullPointerException: null
	at com.sun.org.apache.xerces.internal.impl.xs.traversers.XSDHandler.traverseSchemas(XSDHandler.java:1445) ~[na:1.7.0_71]
	at com.sun.org.apache.xerces.internal.impl.xs.traversers.XSDHandler.parseSchema(XSDHandler.java:630) ~[na:1.7.0_71]
	at com.sun.org.apache.xerces.internal.impl.xs.XMLSchemaLoader.loadSchema(XMLSchemaLoader.java:616) ~[na:1.7.0_71]
	at com.sun.org.apache.xerces.internal.impl.xs.XMLSchemaLoader.loadGrammar(XMLSchemaLoader.java:574) ~[na:1.7.0_71]
	at com.sun.org.apache.xerces.internal.impl.xs.XMLSchemaLoader.loadGrammar(XMLSchemaLoader.java:540) ~[na:1.7.0_71]
	at com.sun.org.apache.xerces.internal.jaxp.validation.XMLSchemaFactory.newSchema(XMLSchemaFactory.java:252) ~[na:1.7.0_71]
	at javax.xml.validation.SchemaFactory.newSchema(SchemaFactory.java:627) ~[na:1.7.0_71]
	at javax.xml.validation.SchemaFactory.newSchema(SchemaFactory.java:659) ~[na:1.7.0_71]
	at com.onelogin.saml2.util.SchemaFactory.loadFromUrl(SchemaFactory.java:25) ~[classes/:na]
	at com.onelogin.saml2.util.Util.validateXML(Util.java:215) ~[classes/:na]
```

**Comment by pitbulk** [comment]
Merged the PR
